name: Generate Premium T-shirt Design

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install pillow google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

    - name: Run design generator
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        DRIVE_FOLDER_ID:    ${{ secrets.DRIVE_FOLDER_ID }}
      run: python generate_design.py
