name: Generate T-shirt Design

on:
  workflow_dispatch:  # manual run
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pillow requests pydrive

    - name: Run Python script
      env:
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      run: python generate_design.py
