name: Generate T-Shirt Design

on:
  workflow_dispatch:  # Manual run
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pillow pydrive2 requests

    - name: Run generate_design.py
      env:
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      run: python generate_design.py
