name: Generate and Upload T-shirt Designs

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create service_account.json
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 -d > service_account.json

    - name: Run generator
      env:
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      run: python generate_design.py
