name: Generate T-shirt Design

on:
  workflow_dispatch:  # manual run
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pillow requests google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

    - name: Run Python script
      env:
        HORDE_API_KEY: ${{ secrets.HORDE_API_KEY }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      run: python generate_design.py
